version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    user: root
    ports:
      - 1433:1433
    environment:
        SA_PASSWORD: 'Your_password123'
        ACCEPT_EULA: 'Y'
    volumes:
      - db_volume:/var/opt/mssql/data

volumes:
  db_volume: