// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using StockTrader.Portfolios.Projection.Sql;

namespace StockTrader.Portfolios.Projection.Sql.Migrations
{
    [DbContext(typeof(PortfoliosSqlReadContext))]
    [Migration("00000000000000_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
