// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockTrader.Portfolios.Persistence;

namespace StockTrader.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20210911191431_CreatePortfolio")]
    partial class CreatePortfolio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StockTrader.Portfolios.Persistence.DataModels.HoldingData", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ShareCount")
                        .HasColumnType("int");

                    b.HasKey("PortfolioId", "Symbol");

                    b.ToTable("Holding");
                });

            modelBuilder.Entity("StockTrader.Portfolios.Persistence.DataModels.OrderData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PriceLimit")
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("Shares")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("StockTrader.Portfolios.Persistence.DataModels.PortfolioData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Portfolio");
                });

            modelBuilder.Entity("StockTrader.Portfolios.Persistence.DataModels.HoldingData", b =>
                {
                    b.HasOne("StockTrader.Portfolios.Persistence.DataModels.PortfolioData", "Portfolio")
                        .WithMany("Holdings")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("StockTrader.Portfolios.Persistence.DataModels.OrderData", b =>
                {
                    b.HasOne("StockTrader.Portfolios.Persistence.DataModels.PortfolioData", "Portfolio")
                        .WithMany("Orders")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("StockTrader.Portfolios.Persistence.DataModels.PortfolioData", b =>
                {
                    b.Navigation("Holdings");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
